//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefExplorer.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefExplorer.Gui.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActivityIndicator {
            get {
                object obj = ResourceManager.GetObject("ActivityIndicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Reference Explorer.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///	font: 0.8em Tahoma, Arial;
        ///	color: #444;
        ///}
        ///
        ///td
        ///{
        ///    font-size: 0.8em;
        ///}
        ///
        ///h1
        ///{
        ///    font-size: 1.1em;
        ///}
        ///
        ///.
        /// </summary>
        internal static string DefaultCss {
            get {
                return ResourceManager.GetString("DefaultCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid path..
        /// </summary>
        internal static string EnterPath {
            get {
                return ResourceManager.GetString("EnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;In Progress&lt;/title&gt;
        ///    &lt;link type=&apos;text/css&apos; rel=&apos;Stylesheet&apos; href=&apos;Default.css&apos; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table width=&quot;100%&quot; height=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;center&quot;&gt;
        ///                &lt;img alt=&quot;&quot; src=&quot;ActivityIndicator.gif&quot; align=&quot;top&quot; /&gt;
        ///                Loading...
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/table&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string InProgressHtml {
            get {
                return ResourceManager.GetString("InProgressHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Welcome&lt;/title&gt;
        ///    &lt;link type=&apos;text/css&apos; rel=&apos;Stylesheet&apos; href=&apos;Default.css&apos; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;.NET Reference Explorer&lt;/h1&gt;
        ///    &lt;p&gt;
        ///    This tool helps you to check, on which other assemblies, a certain .NET assembly relies on. It displays the dependencies in a directed graph and informs you, if the referenced assemblies are available and which versions are required.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;To start, either &lt;strong&gt;drag and drop the as [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeHtml {
            get {
                return ResourceManager.GetString("WelcomeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You only can drop folders, DLLs and EXEs..
        /// </summary>
        internal static string WrongDrop {
            get {
                return ResourceManager.GetString("WrongDrop", resourceCulture);
            }
        }
    }
}
